settings:
  dir: D:\Projekte\sididraw

database:
  port: 27017
  host: localhost

imagemagic:
  dir: D:\Projekte\sididraw\tmp
  executable: D:\Projekte\sididraw\imagemagic\convert.exe
  file: out{}.png
  command: "{executable} {command} {inputfile} {outputfile}"

imagej:
  dir: D:\Projekte\sididraw\tmp
  executable: D:\Projekte\Fiji.app\ImageJ-win64.exe
  file: out{}.png
  command: "{executable} --headless -macro {macro} {inputfile}#{outputfile}"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
