settings:
  dir: D:\Projekte\sididraw

database:
  port: 27017
  host: localhost

imagemagic:
  dir: D:\Projekte\sididraw\imagemagic
  executable: convert.exe
  file: out{}.png
  command: "{dir}/{executable} {command} {inputfile} {outputfile}"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
