settings:
  dir: D:\Projekte\sididraw

database:
  port: 27017
  host: localhost

imagemagic:
  dir: R:\
  executable: D:\Projekte\sididraw\imagemagic\convert.exe
  file: out{}.png
  command: "{executable} {command} {inputfile} {outputfile}"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
